from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
from datetime import datetime


# =========================================================
# COLOR PALETTE
# =========================================================
BLUE       = colors.HexColor("#2563EB")
CYAN       = colors.HexColor("#06B6D4")
GREEN      = colors.HexColor("#10B981")
ORANGE     = colors.HexColor("#F59E0B")
RED        = colors.HexColor("#EF4444")
DARK_RED   = colors.HexColor("#DC2626")
DARK_BG    = colors.HexColor("#0F172A")
SLATE      = colors.HexColor("#1E293B")
LIGHT_GRAY = colors.HexColor("#F1F5F9")
MID_GRAY   = colors.HexColor("#CBD5E1")
WHITE      = colors.white
BLACK      = colors.HexColor("#020617")


# =========================================================
# BILINGUAL REPORT STRINGS
# =========================================================
REPORT_TEXTS = {
    "en": {
        "report_title":    "SME RISK INTELLIGENCE REPORT",
        "powered_by":      "Powered by SME Risk Intelligence AI",
        "generated":       "Generated",
        "s1_title":        "1. RISK ASSESSMENT SUMMARY",
        "risk_score":      "Risk Score",
        "confidence_lbl":  "Confidence",
        "risk_class":      "Risk Classification",
        "s2_title":        "2. AI ANALYSIS & EXPLANATION",
        "s3_title":        "3. FINANCIAL INDICATORS",
        "metric":          "Metric",
        "value":           "Value",
        "status":          "Status",
        "inc_avg":         "Monthly Income Average",
        "credit_req":      "Credit Amount Requested",
        "deposits":        "Total Deposits (3M)",
        "dti":             "Debt-to-Income Ratio",
        "rev_vol":         "Revenue Volatility",
        "nsf":             "NSF Count (3M)",
        "neg_days":        "Negative Balance Days",
        "credit_score":    "Owner Credit Score",
        "biz_age":         "Business Age",
        "months":          "months",
        "strong":          "✓ Strong",
        "monitor":         "⚠ Monitor",
        "adequate":        "✓ Adequate",
        "low":             "⚠ Low",
        "healthy":         "✓ Healthy",
        "elevated":        "✗ Elevated",
        "stable":          "✓ Stable",
        "volatile":        "⚠ Volatile",
        "clean":           "✓ Clean",
        "risky":           "✗ Risky",
        "ok":              "✓ OK",
        "frequent":        "✗ Frequent",
        "established":     "✓ Established",
        "early":           "⚠ Early-Stage",
        "dash":            "—",
        "s4_title":        "4. STRATEGIC RECOMMENDATIONS",
        "rec_num":         "#",
        "recommendation":  "Recommendation",
        "priority":        "Priority",
        "s5_title":        "5. LENDING DECISION",
        "approved_title":  "APPROVED — PROCEED WITH STANDARD TERMS",
        "approved_detail": (
            "The applicant demonstrates a strong financial profile with stable income, "
            "healthy credit metrics, and low operational risk. "
            "Standard lending terms are recommended."
        ),
        "cond_title":      "CONDITIONAL — ENHANCED DUE DILIGENCE REQUIRED",
        "cond_detail":     (
            "Moderate risk indicators detected. Lending may proceed with additional collateral, "
            "reduced facility size, or structured repayment monitoring."
        ),
        "declined_title":  "DECLINED — RISK EXCEEDS ACCEPTABLE THRESHOLD",
        "declined_detail": (
            "Multiple high-risk indicators identified. Lending is not recommended at this stage. "
            "The applicant should address key weaknesses before reapplication."
        ),
        "footer": (
            "CONFIDENTIAL  ·  SME Risk Intelligence Platform  ·  "
            "Report ID: RI-{rid}  ·  "
            "This report is generated by an AI system and is for informational purposes only."
        ),
        "conf_high":   "High",
        "conf_medium": "Medium",
        "conf_low":    "Low",
        "low_risk":    "LOW RISK",
        "med_risk":    "MEDIUM RISK",
        "high_risk":   "HIGH RISK",
    },
    "ar": {
        "report_title":    "تقرير ذكاء مخاطر المشروعات الصغيرة والمتوسطة",
        "powered_by":      "مدعوم بمنصة ذكاء المخاطر للمشروعات الصغيرة والمتوسطة",
        "generated":       "تاريخ الإنشاء",
        "s1_title":        "١. ملخص تقييم المخاطر",
        "risk_score":      "درجة المخاطر",
        "confidence_lbl":  "الثقة",
        "risk_class":      "تصنيف المخاطر",
        "s2_title":        "٢. تحليل وشرح الذكاء الاصطناعي",
        "s3_title":        "٣. المؤشرات المالية",
        "metric":          "المؤشر",
        "value":           "القيمة",
        "status":          "الحالة",
        "inc_avg":         "متوسط الدخل الشهري",
        "credit_req":      "مبلغ الائتمان المطلوب",
        "deposits":        "إجمالي الإيداعات (3 أشهر)",
        "dti":             "نسبة الدين إلى الدخل",
        "rev_vol":         "تذبذب الإيرادات",
        "nsf":             "عدد حالات NSF (3 أشهر)",
        "neg_days":        "أيام الرصيد السلبي",
        "credit_score":    "الدرجة الائتمانية للمالك",
        "biz_age":         "عمر الشركة",
        "months":          "شهر",
        "strong":          "✓ قوي",
        "monitor":         "⚠ يحتاج متابعة",
        "adequate":        "✓ كافٍ",
        "low":             "⚠ منخفض",
        "healthy":         "✓ صحي",
        "elevated":        "✗ مرتفع",
        "stable":          "✓ مستقر",
        "volatile":        "⚠ متذبذب",
        "clean":           "✓ نظيف",
        "risky":           "✗ خطر",
        "ok":              "✓ مقبول",
        "frequent":        "✗ متكرر",
        "established":     "✓ راسخة",
        "early":           "⚠ مبكرة",
        "dash":            "—",
        "s4_title":        "٤. التوصيات الاستراتيجية",
        "rec_num":         "#",
        "recommendation":  "التوصية",
        "priority":        "الأولوية",
        "s5_title":        "٥. قرار الإقراض",
        "approved_title":  "موافقة — المضي بالشروط المعيارية",
        "approved_detail": (
            "يُظهر مقدم الطلب ملفًا ماليًا قويًا مع دخل مستقر "
            "ومؤشرات ائتمانية سليمة ومخاطر تشغيلية منخفضة. "
            "يُوصى بتطبيق شروط الإقراض المعيارية."
        ),
        "cond_title":      "مشروط — مطلوب مراجعة معمّقة",
        "cond_detail":     (
            "تم رصد مؤشرات مخاطر متوسطة. يمكن المضي في الإقراض "
            "مع ضمانات إضافية أو تقليل حجم التسهيل "
            "أو خضوع السداد لرقابة منظمة."
        ),
        "declined_title":  "رفض — المخاطر تتجاوز الحد المقبول",
        "declined_detail": (
            "تم رصد مؤشرات مخاطر مرتفعة متعددة. لا يُنصح بالإقراض في هذه المرحلة. "
            "يجب على مقدم الطلب معالجة نقاط الضعف الرئيسية قبل إعادة التقدم."
        ),
        "footer": (
            "سري  ·  منصة ذكاء المخاطر للمشروعات الصغيرة والمتوسطة  ·  "
            "رقم التقرير: RI-{rid}  ·  "
            "هذا التقرير مُولَّد بواسطة نظام ذكاء اصطناعي وهو للأغراض المعلوماتية فقط."
        ),
        "conf_high":   "عالية",
        "conf_medium": "متوسطة",
        "conf_low":    "منخفضة",
        "low_risk":    "مخاطر منخفضة",
        "med_risk":    "مخاطر متوسطة",
        "high_risk":   "مخاطر عالية",
    }
}


# =========================================================
# HELPERS
# =========================================================
def _risk_color(risk_score):
    if risk_score < 40:
        return GREEN
    elif risk_score < 70:
        return ORANGE
    return RED


def _risk_label(risk_score, tx):
    if risk_score < 40:
        return tx["low_risk"]
    elif risk_score < 70:
        return tx["med_risk"]
    return tx["high_risk"]


def _confidence_label(confidence, tx):
    if confidence >= 80:
        return tx["conf_high"]
    elif confidence >= 65:
        return tx["conf_medium"]
    return tx["conf_low"]


# =========================================================
# PDF REPORT GENERATOR
# =========================================================
def generate_pdf(
    risk_score,
    confidence,
    explanation,
    result=None,
    input_df=None,
    recommendations=None,
    lang="en"
):
    tx = REPORT_TEXTS.get(lang, REPORT_TEXTS["en"])

    # For Arabic PDFs use right-align; reportlab doesn't do
    # full BiDi but numeric/latin data renders fine LTR inside cells.
    txt_align = TA_RIGHT if lang == "ar" else TA_LEFT

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm
    )

    styles = getSampleStyleSheet()

    # ── Styles ────────────────────────────────────────────
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Normal"],
        fontSize=22,
        fontName="Helvetica-Bold",
        textColor=WHITE,
        alignment=TA_CENTER,
        spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=MID_GRAY,
        alignment=TA_CENTER,
        spaceAfter=2
    )
    section_header_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Normal"],
        fontSize=13,
        fontName="Helvetica-Bold",
        textColor=BLUE,
        spaceBefore=14,
        spaceAfter=6,
        alignment=txt_align
    )
    body_style = ParagraphStyle(
        "BodyText2",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=BLACK,
        leading=16,
        spaceAfter=4,
        alignment=txt_align
    )

    content = []

    # ── Header Banner ─────────────────────────────────────
    header_data = [[Paragraph(tx["report_title"], title_style)]]
    header_table = Table(header_data, colWidths=[doc.width])
    header_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), DARK_BG),
        ("TOPPADDING",    (0, 0), (-1, -1), 20),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
        ("LEFTPADDING",   (0, 0), (-1, -1), 20),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 20),
    ]))
    content.append(header_table)
    content.append(Spacer(1, 6))

    sub_data = [[
        Paragraph(
            f"{tx['generated']}: {datetime.now().strftime('%Y-%m-%d  |  %H:%M')}  ·  {tx['powered_by']}",
            subtitle_style
        )
    ]]
    sub_table = Table(sub_data, colWidths=[doc.width])
    sub_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), SLATE),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 20),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 20),
    ]))
    content.append(sub_table)
    content.append(Spacer(1, 16))

    # ── Section 1: Scorecards ─────────────────────────────
    content.append(Paragraph(tx["s1_title"], section_header_style))
    content.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=10))

    risk_color = _risk_color(risk_score)
    conf_label = _confidence_label(confidence, tx)
    risk_lbl   = _risk_label(risk_score, tx)

    sc_val_style = ParagraphStyle(
        "SCV", fontSize=28, fontName="Helvetica-Bold",
        textColor=WHITE, alignment=TA_CENTER
    )
    sc_lbl_style = ParagraphStyle(
        "SCL", fontSize=9, fontName="Helvetica",
        textColor=MID_GRAY, alignment=TA_CENTER
    )

    scorecard_data = [[
        Paragraph(f"<b>{risk_score}%</b>",  sc_val_style),
        Paragraph(f"<b>{confidence}%</b>",  sc_val_style),
        Paragraph(f"<b>{risk_lbl}</b>",
                  ParagraphStyle("SC3", fontSize=16, fontName="Helvetica-Bold",
                                 textColor=WHITE, alignment=TA_CENTER)),
    ], [
        Paragraph(tx["risk_score"],                  sc_lbl_style),
        Paragraph(f"{tx['confidence_lbl']} · {conf_label}", sc_lbl_style),
        Paragraph(tx["risk_class"],                  sc_lbl_style),
    ]]

    col_w = doc.width / 3
    scorecard = Table(scorecard_data, colWidths=[col_w, col_w, col_w])
    scorecard.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, -1), risk_color),
        ("BACKGROUND",    (1, 0), (1, -1), BLUE),
        ("BACKGROUND",    (2, 0), (2, -1), DARK_BG),
        ("TOPPADDING",    (0, 0), (-1, -1), 16),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("GRID",          (0, 0), (-1, -1), 1, WHITE),
    ]))
    content.append(scorecard)
    content.append(Spacer(1, 14))

    # ── Section 2: Explanation ────────────────────────────
    content.append(Paragraph(tx["s2_title"], section_header_style))
    content.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=10))

    exp_box = [[
        Paragraph(explanation, ParagraphStyle(
            "Exp", fontSize=10, fontName="Helvetica",
            textColor=BLACK, leading=17, spaceAfter=0,
            alignment=txt_align
        ))
    ]]
    exp_table = Table(exp_box, colWidths=[doc.width])
    exp_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), LIGHT_GRAY),
        ("TOPPADDING",    (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("BOX",           (0, 0), (-1, -1), 1.5, BLUE),
    ]))
    content.append(exp_table)
    content.append(Spacer(1, 14))

    # ── Section 3: Financial Indicators ──────────────────
    if input_df is not None:
        content.append(Paragraph(tx["s3_title"], section_header_style))
        content.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=10))

        row = input_df.iloc[0]

        fin_rows = [
            [tx["metric"], tx["value"], tx["status"]],
            [tx["inc_avg"],
             f"EGP {row.get('monthly_income_avg', 0):,.0f}",
             tx["strong"] if row.get("monthly_income_avg", 0) > 50000 else tx["monitor"]],
            [tx["credit_req"],
             f"EGP {row.get('credit_amount', 0):,.0f}",
             tx["dash"]],
            [tx["deposits"],
             f"EGP {row.get('total_deposits_3m', 0):,.0f}",
             tx["adequate"] if row.get("total_deposits_3m", 0) > row.get("credit_amount", 1) else tx["low"]],
            [tx["dti"],
             f"{row.get('dti_monthly', 0):.2%}",
             tx["healthy"] if row.get("dti_monthly", 0) < 0.45 else tx["elevated"]],
            [tx["rev_vol"],
             f"{row.get('revenue_volatility_3m', 0):.2%}",
             tx["stable"] if row.get("revenue_volatility_3m", 0) < 0.25 else tx["volatile"]],
            [tx["nsf"],
             str(int(row.get("nsf_count_3m", 0))),
             tx["clean"] if row.get("nsf_count_3m", 0) <= 2 else tx["risky"]],
            [tx["neg_days"],
             str(int(row.get("negative_days_3m", 0))),
             tx["ok"] if row.get("negative_days_3m", 0) <= 10 else tx["frequent"]],
            [tx["credit_score"],
             str(int(row.get("owner_credit_score", 0))),
             tx["strong"] if row.get("owner_credit_score", 0) > 700 else tx["monitor"]],
            [tx["biz_age"],
             f"{int(row.get('business_age_months', 0))} {tx['months']}",
             tx["established"] if row.get("business_age_months", 0) >= 24 else tx["early"]],
        ]

        col_widths = [doc.width * 0.45, doc.width * 0.30, doc.width * 0.25]
        fin_table = Table(fin_rows, colWidths=col_widths)
        fin_table.setStyle(TableStyle([
            ("BACKGROUND",     (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
            ("FONTNAME",       (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",       (0, 0), (-1, 0), 10),
            ("ALIGN",          (0, 0), (-1, -1), "RIGHT" if lang == "ar" else "LEFT"),
            ("ALIGN",          (1, 0), (2, -1), "CENTER"),
            ("FONTNAME",       (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",       (0, 1), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("GRID",           (0, 0), (-1, -1), 0.5, MID_GRAY),
            ("TOPPADDING",     (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 8),
            ("LEFTPADDING",    (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",   (0, 0), (-1, -1), 10),
        ]))
        content.append(fin_table)
        content.append(Spacer(1, 14))

    # ── Section 4: Recommendations ───────────────────────
    if recommendations:
        content.append(Paragraph(tx["s4_title"], section_header_style))
        content.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=10))

        priority_colors = {
            "LOW":      GREEN,
            "MEDIUM":   ORANGE,
            "HIGH":     RED,
            "CRITICAL": DARK_RED
        }

        rec_header = [[tx["rec_num"], tx["recommendation"], tx["priority"]]]
        rec_rows = rec_header + [
            [
                str(i + 1),
                Paragraph(
                    f"<b>{rec['title']}</b><br/><font size=8>{rec['description']}</font>",
                    ParagraphStyle("RB", fontSize=9, fontName="Helvetica",
                                   leading=14, alignment=txt_align)
                ),
                Paragraph(
                    f"<b>{rec['priority']}</b>",
                    ParagraphStyle(
                        "RP", fontSize=9, fontName="Helvetica-Bold",
                        textColor=priority_colors.get(rec["priority"], BLUE),
                        alignment=TA_CENTER
                    )
                )
            ]
            for i, rec in enumerate(recommendations)
        ]

        rec_table = Table(
            rec_rows,
            colWidths=[doc.width * 0.06, doc.width * 0.72, doc.width * 0.22]
        )
        rec_table.setStyle(TableStyle([
            ("BACKGROUND",     (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
            ("FONTNAME",       (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",       (0, 0), (-1, 0), 10),
            ("ALIGN",          (0, 0), (-1, -1), "LEFT"),
            ("ALIGN",          (2, 0), (2, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("GRID",           (0, 0), (-1, -1), 0.5, MID_GRAY),
            ("TOPPADDING",     (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 10),
            ("LEFTPADDING",    (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",   (0, 0), (-1, -1), 10),
            ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ]))
        content.append(rec_table)
        content.append(Spacer(1, 14))

    # ── Section 5: Lending Decision ───────────────────────
    content.append(Paragraph(tx["s5_title"], section_header_style))
    content.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=10))

    if risk_score < 40:
        decision_title  = tx["approved_title"]
        decision_detail = tx["approved_detail"]
        decision_color  = GREEN
    elif risk_score < 70:
        decision_title  = tx["cond_title"]
        decision_detail = tx["cond_detail"]
        decision_color  = ORANGE
    else:
        decision_title  = tx["declined_title"]
        decision_detail = tx["declined_detail"]
        decision_color  = RED

    decision_data = [[
        Paragraph(decision_title, ParagraphStyle(
            "Dec", fontSize=13, fontName="Helvetica-Bold",
            textColor=WHITE, alignment=TA_CENTER
        )),
    ], [
        Paragraph(decision_detail, ParagraphStyle(
            "DecD", fontSize=10, fontName="Helvetica",
            textColor=BLACK, leading=16, alignment=txt_align
        )),
    ]]
    dec_table = Table(decision_data, colWidths=[doc.width])
    dec_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), decision_color),
        ("BACKGROUND",    (0, 1), (-1, 1), LIGHT_GRAY),
        ("TOPPADDING",    (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("BOX",           (0, 0), (-1, -1), 1.5, decision_color),
    ]))
    content.append(dec_table)
    content.append(Spacer(1, 20))

    # ── Footer ────────────────────────────────────────────
    rid = datetime.now().strftime("%Y%m%d%H%M%S")
    footer_data = [[
        Paragraph(
            tx["footer"].format(rid=rid),
            ParagraphStyle(
                "Footer", fontSize=7, fontName="Helvetica",
                textColor=MID_GRAY, alignment=TA_CENTER
            )
        )
    ]]
    footer_table = Table(footer_data, colWidths=[doc.width])
    footer_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), DARK_BG),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    content.append(footer_table)

    doc.build(content)
    buffer.seek(0)
    return buffer.read()